import { StyleSheet } from "react-native";

export const CommonStyles = StyleSheet.create({
  textItem: {
    fontSize: 40,
    marginTop: -60,
  },
  container: {
    flex: 1,
    backgroundColor: "#fff",
    paddingTop: 15,
    paddingBottom: 15,
    paddingHorizontal: 7,
    marginTop: 7,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingStart: 20,
    paddingEnd: 110,
    borderColor: "lightblue",
    borderWidth: 2,
    borderRadius: 5,
    marginStart: 5,
    marginEnd: 5,
    marginTop: 5,
    marginBottom: -8,
  },
  headerText: {
    fontWeight: "bold",
    fontSize: 20,
    padding: 15,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    borderColor: "lightblue",
    borderWidth: 3,
    borderRadius: 5,
    margin: 5,
    paddingEnd: 20,
    paddingStart: 20,
    paddingTop: 10,
    justifyContent: "space-between",
  },
  nameColumn: {
    flex: 0.8,
    flexDirection: "row",
    paddingEnd: 40,
    justifyContent: "space-between",
  },
  buttonColumn: {
    flex: 0.2,
    paddingBottom: 10,
  },
  buttonAddition: {
    backgroundColor: "green",
    borderRadius: 5,
    borderWidth: 2,
    margin: 5,
    alignItems: "center",
  },
  buttonEditDelete: {
    flexDirection: "row",
    marginTop: 50,
    marginLeft: -260,
  },
  buttonEdit: {
    backgroundColor: "orange",
    borderRadius: 5,
    borderWidth: 2,
    margin: 2,
    alignItems: "center",
  },
  buttonDelete: {
    backgroundColor: "red",
    borderRadius: 5,
    borderWidth: 2,
    margin: 2,
    alignItems: "center",
  },
  buttonSubtraction: {
    backgroundColor: "red",
    marginBottom: -120,
    borderRadius: 5,
    borderWidth: 2,
    margin: 5,
    alignItems: "center",
  },
  disabledButton: {
    opacity: 0.5,
  },
  buttonText: {
    borderRadius: 5,
    fontSize: 40,
    margin: 5,
    alignItems: "center",
  },
  input: {
    borderRadius: 5,
    fontSize: 30,
    margin: 5,
    alignItems: "center",
  },
});
